<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


<h3> Get to Know a numpy Array </h3>


You will use the numpy array <code> A</code> for the following 


In [3]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) type using the function type 


In [4]:
type(A)

numpy.ndarray

2) the shape of the array 


In [5]:
A.shape

(3, 2)

3) the type of data in the array 


In [6]:
A.dtype

dtype('int32')

4) Find the second row of the numpy array <code>A</code>:


In [9]:
A[1:2]

array([[21, 22]])

<h3> Two kinds of Multiplying  </h3>


you will use the following numpy arrays for the next questions 


In [11]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])
A
B

array([[1, 0],
       [0, 1]])

1) multiply array <code> A </code> and <code>B</code>


In [12]:
A*B

array([[11,  0],
       [ 0, 22]])

2)  Perform matrix multiplication on array <code> A</code> and <code> B</code> (order will not matter in this case) 


In [13]:
np.dot(A,B)

array([[11, 12],
       [21, 22]])

In [14]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B) 

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
