# NumPy
Welcome to the fourth lesson! This Jupyter Notebook file is meant to accompany **L04 - NumPy.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

1. <font color=blue>**Module**</font> is a collection of functions
2. <font color=blue>**Package**</font> is collection of modules.

### 1. Introduction to NumPy

In [1]:
import numpy as np

### 2. NumPy Arrays
All objects in a Numpy array  must be same type of object. 
- So you can't mix floats and integers
- You can't mix strings and floats

You can create a NumPy array by passing a list into the array function

In [2]:
array_1 = np.array([1,2,3,4,5])   # List got transformed into array
print(array_1)
print(type(array_1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# When you pass a list of different object types
# NumPy will conver each object into string
array_2 = np.array([1,2,'three', 4, 5]) 
print(array_2) 

['1' '2' 'three' '4' '5']


In [4]:
array_3 = np.array([1,2,3.0,4,5])
print(array_3)

[1. 2. 3. 4. 5.]


In [5]:
array_4 = np.array([[1, 2, 3], [4, 5, 6]]) # Pass-in a list of 2 lists
print(array_4)        # display array
print('---')
print(array_4.shape)  # display the shape of array_4

[[1 2 3]
 [4 5 6]]
---
(2, 3)


<font color = 'blue'> **EXERCISE 2.1** </font>

In [6]:
array_1 = np.array([ [1,2], [3,4], [5,6] ])
print(array_1)
print('---')
print(array_1.shape)

[[1 2]
 [3 4]
 [5 6]]
---
(3, 2)


In [7]:
# Reshape and transpose
array_1 = array_1.reshape(2,3)   # Number of Rows you want, Number of Columns you want
array_1

array([[1, 2, 3],
       [4, 5, 6]])

**Ways to interact with NumPy Arrays**

1. Reshape to the original dimensions with 3 rows and 2 columns

In [8]:
# Reshape to the original dimensions with 3 rows and 2 columns
array_1 = array_1.reshape(3,2)   
print('Original Dimensions')
print(array_1)
print('---')

# transpose to 2 rows and 3 columns
print('Transposed from Original')
print(array_1.transpose())

Original Dimensions
[[1 2]
 [3 4]
 [5 6]]
---
Transposed from Original
[[1 3 5]
 [2 4 6]]


2. Access elements in lists vs. NumPy Array

In [9]:
list_1 = [1, 2, 3, 4, 5]
# Index   0  1  2  3  4

print(list_1[4])   # Print index 4
print(list_1[:3])  # Display first 3 elements; Or, access 0,1,2 (exclude index 3)

5
[1, 2, 3]


In [10]:
array_x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array_x[1,2]

6

In [11]:
print(array_x[0:2, 0:2]) # Range of Rows that you want, Range of columns 

[[1 2]
 [4 5]]


<font color = 'blue'> **EXERCISE 2.2** </font>

In [12]:
array_a = np.array([
    ['n', 'e', 'w', 'y', '_', 's'],
    ['t', 'o', 'c', 'k', '_', 'r'],
    ['_', '_', '_', 'k', 'e', 'x'],
    ['c', 'h', 'a', 'n', 'g', 'e']
])

In [13]:
# Reshape to 6 rows and 4 columns and print
array_b = array_a.reshape(6,4)
print(array_b)


[['n' 'e' 'w' 'y']
 ['_' 's' 't' 'o']
 ['c' 'k' '_' 'r']
 ['_' '_' '_' 'k']
 ['e' 'x' 'c' 'h']
 ['a' 'n' 'g' 'e']]


In [14]:
# Print 'new york stock exchange' from array_b (one word per line)
print(array_b[0, :3])                    # print first row with first 3 columns
print(array_b[:4, 3])                    # print first 4 rows, and index 3 
print(array_b[1, 1:], array_b[2, :2])
print(array_b[4, :],  array_b[5, :] )    

['n' 'e' 'w']
['y' 'o' 'r' 'k']
['s' 't' 'o'] ['c' 'k']
['e' 'x' 'c' 'h'] ['a' 'n' 'g' 'e']


### 3. NumPy Array Functions

In [15]:
array_x = np.array([
    [1,2],
    [3,4]
])

array_y = np.array([
    [5,6],
    [7,8]
])

array_z = array_x + array_y   # Add elements in 2d-arrays by corresponding positions
print(array_z)
print('---')
print(array_z + 10)           # Add 10 to each element

# Useful NumPy functions
# np.round()
# np.sqrt()
# np.abs()
# np.power()

print('---')
root_z = np.sqrt(array_z)
print(root_z)
print('---')
print(np.round(root_z, 2))
print('---')
print('Sum of all objects = {}'.format( np.sum(array_z) ))
print('Min = {}'.format( np.min(array_z) ))
print('Max = {}'.format( np.max(array_z) ))

print('---')
print('Sum Across Rows = {}'.format( np.sum(array_z, axis=0) ))
print('Min Across Columns = {}'.format( np.min(array_z, axis=1) ))
print('Max Across Columns = {}'.format( np.max(array_z, axis=1) ))

[[ 6  8]
 [10 12]]
---
[[16 18]
 [20 22]]
---
[[2.44948974 2.82842712]
 [3.16227766 3.46410162]]
---
[[2.45 2.83]
 [3.16 3.46]]
---
Sum of all objects = 36
Min = 6
Max = 12
---
Sum Across Rows = [16 20]
Min Across Columns = [ 6 10]
Max Across Columns = [ 8 12]


<font color = 'blue'> **EXERCISE 3.1** </font>
We’re looking at 3 tech companies, 3 financial companies and 3 healthcare companies. Each of these industries is organized into a column. Execute the cell to define those arrays and complete the following steps:

1. Create a new array called **price_increases** by subtracting **current_prices** from **target_prices**
2. Print **price_increases**
3. Create a new array called **returns** by dividing **price_increases** by **current_prices** and rounding the result to 3 decimal places
4. Print **returns**
5. Print the maximum value in returns
6. Print the mean **returns** for each industry column rounded to 3 decimal places


In [16]:
current_prices = np.array([
    [223.84, 113.5, 139.49],
    [113.37, 30.37, 265.31],
    [1177.98, 54.73, 42.96],
])

target_prices = np.array([
    [232.27, 112.15, 144.2],
    [122.3, 34.33, 284.14],
    [1384.89, 62.12, 43.06],
]) 

In [17]:
price_increases = target_prices - current_prices
print(price_increases)
print('---')

returns = np.round(price_increases / current_prices, 3)
print(returns)
print('---')

print(np.max(returns))
print('---')

print(np.round(np.mean(returns, axis=0), 3))

[[ 8.4300e+00 -1.3500e+00  4.7100e+00]
 [ 8.9300e+00  3.9600e+00  1.8830e+01]
 [ 2.0691e+02  7.3900e+00  1.0000e-01]]
---
[[ 0.038 -0.012  0.034]
 [ 0.079  0.13   0.071]
 [ 0.176  0.135  0.002]]
---
0.176
---
[0.098 0.084 0.036]


### 4. NumPy Random Tools

In [18]:
# low = lower boundary (inclusive)
# high = upper boundary (exclusive)
# size = the number of random numbers you want to generate

# Generate Random number from 1 to 10
print(np.random.randint(low=1, high=11, size=1))

[8]


In [19]:
rand_array = np.random.randint(low=1, high=11, size=10)
print(rand_array)

print(rand_array.shape)



[10  1  4  2  6  9  3  5  2  3]
(10,)


In [20]:
rand_array = rand_array.reshape(5,2)
print(rand_array)

[[10  1]
 [ 4  2]
 [ 6  9]
 [ 3  5]
 [ 2  3]]


In [21]:
rand_array = np.random.randint(low=1, high=11, size=(5,2)) # 5 rows and 2 columns
print(rand_array)

print(rand_array.shape)

[[ 6  5]
 [ 8  6]
 [ 7 10]
 [ 8  3]
 [ 4  8]]
(5, 2)


In [22]:
ordered_array = np.array(range(1,11))
print(ordered_array)

[ 1  2  3  4  5  6  7  8  9 10]


Samping with and without replacement

In [23]:
np.random.seed(10)
# Sampling with Replacement
print(np.random.choice(ordered_array, 5)) 

[10  5  1  2 10]


In [24]:
np.random.seed(10)
# Sampling without Replacement
# Only unique values; Can only be chosen once
print(np.random.choice(ordered_array, 5, replace=False)) 


[9 3 6 7 4]


Brief Detour on Range, which creates a range of numbers in sequence.
- This is good for creating an iteratable 

- In the below example, starting with 1 and **excluding** 6

In [25]:
for number in range(1,6):
    print(number)

1
2
3
4
5


<font color = 'blue'> **EXERCISE 4.1** </font>

1. Set the random seed to 99
2. Generate an array of random integers between 1 and 25 named rand_array with 5 rows and 5 columns
3. Print rand_array

In [26]:
# Set the random seed to 99
np.random.seed(99) 

# Generate an array of random integers between 1 and 25 named rand_array 
# with 5 rows and 5 columns
rand_array=np.random.randint(1,26, size=(5,5))
print(rand_array)

[[ 2  4  9 10  9]
 [19  5  6 21  2]
 [24  4 24 18  2]
 [17  7 12 21 24]
 [ 3  1 13  9  9]]


4. Choose and print a random sample of 5 numbers from the **second row** of **rand_array** with replacement

In [27]:
print(np.random.choice(rand_array[1, :], 5)) # Sampling with Replacement

[ 2  5 21  6 21]


5. Generate an array of ordered integers from 1 to 25 named ordered_array and **reshape to 5 rows and 5 columns**
6. Print **order_array**

In [28]:
ordered_array = np.array(range(1, 26)).reshape(5,5)
print(ordered_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


7. Choose and print a random sample of 5 numbers from the **third column** of ordered_array without replacement

In [29]:
# Sampling with Replacement
print(np.random.choice(ordered_array[:, 2], 5, replace=False) ) 

[13 18  8  3 23]
